apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-website-deployment
  labels:
    app: audio-website
spec:
  replicas: 4
  selector:
    matchLabels:
      app: audio-website
  template:
    metadata:
      labels:
        app: audio-website
    spec:
      containers:
      - name: audio-website-container
        image: django-docker-build:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: "0"
            memory: "0"
            
