apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  labels:
    app: microservice
spec:
  replicas: 4
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice-container
        image: python-selenium-rumble-bot:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: "0"
            memory: "0"
            