localhost = 'http://127.0.0.1:8000/'
geckoDriverPath = '/Users/administrator/Desktop/Projects/djangoProjects/anew_web/backend/frontend/Driver/geckodriver'

drums_nav_xpath = '/html/body/div/nav/ul/li[1]/a'
bass_nav_xpath = '/html/body/div/nav/ul/li[2]/a'
vox_nav_xpath = '/html/body/div/nav/ul/li[3]/a'
title_nav_xpath = '/html/body/div/h1/a'

drums_nav2 = 'li.list-item2:nth-child(1) > a:nth-child(1)'
bass_nav2 = 'li.list-item2:nth-child(2) > a:nth-child(1)'
vox_nav2 = 'li.list-item2:nth-child(3) > a:nth-child(1)'
about_nav2 = 'li.list-item2:nth-child(4) > a:nth-child(1)'
policy_nav2 = '#menu > li:nth-child(5) > a:nth-child(1)'
main_policy = '.loop-title-drums'

audio_path = '/Users/administrator/Desktop/Projects/djangoProjects/anew_web/backend/frontend/static/mp3/brake_neck_drumloop.mp3'
audio_path_lbdb = '/Users/administrator/Desktop/Projects/djangoProjects/anew_web/backend/frontend/static/mp3/laidback_drum_and_bass_beat_40bpm.mp3'
audio_path_pan = '/Users/administrator/Desktop/Projects/djangoProjects/anew_web/backend/frontend/static/mp3/Pandos.mp3'
audio_path_sob ='/Users/administrator/Desktop/Projects/djangoProjects/anew_web/backend/frontend/static/mp3/Soubbin.mp3'
audio_path_ter = '/Users/administrator/Desktop/Projects/djangoProjects/anew_web/backend/frontend/static/mp3/Tera.mp3'
audio_path_ber = '/Users/administrator/Desktop/Projects/djangoProjects/anew_web/backend/frontend/static/mp3/Beregin.mp3'
